rootProject.name = "identity-hub"

include(":spi:identity-hub-spi")
include(":spi:identity-hub-store-spi")
include(":spi:identity-hub-client-spi")
include(":extensions:identity-hub")
include(":extensions:identity-hub-client")
include(":extensions:identity-did-mock")
include(":identity-hub-core:identity-hub-model")
include(":extensions:identity-hub-verifier")
include(":extensions:identity-hub-jwt-verifier")
include(":client-cli")
include(":system-tests:launcher")
include(":system-tests:tests")
include(":identity-hub-util")
